#!/usr/bin/env python3
"""Build and audit E3 ownership classes without running any search.

The paired design reuses every active L-main network.  It keeps customer
locations, demand, time windows and carbon data fixed, then compares
nearest-depot ownership with one preregistered spatially mixed portfolio.
Mixed ownership is generated by permuting the nearest-depot labels inside
service-shift and demand-quartile blocks.  Fleet adequacy is handled later by
one outcome-blind common-envelope design, so a source network is not excluded
merely because its historical metadata contains only one powertrain.
"""

from __future__ import annotations

from collections import Counter, defaultdict
import csv
import hashlib
import json
from pathlib import Path
import random
import re
import statistics
import subprocess
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
for item in (ROOT / "solver/src", ROOT / "models/src", ROOT):
    if str(item) not in sys.path:
        sys.path.insert(0, str(item))

from setp_solver.profit import infer_customer_home_depots
from setp_solver.search.bundle import load_search_bundle
from setp_solver.search.instance_registry import FORMAL_INSTANCE_ORDER, instance_abs_dir


OUT = ROOT / "baselines/e3_ablation/e3_ownership_class_design_v4_20260713"
PREDECESSOR = ROOT / "baselines/e3_ablation/e3_ownership_class_design_v3_20260713/decision.json"
ACTIVE_MANIFEST = ROOT / "models/data_bundle/generated_instances/L-main/resetp-l-main-main-benchmark.v3.json"
SORIANO_PDF = Path("/Users/zhouleixishu/Zotero/storage/PLSR8GG4/Soriano 等 _ 2023 _ The multi-depot vehicle routing problem with profit fairness.pdf")
BASE_SEED = 202607130000
MOVED_SHARE_MIN = 0.25


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def source_scale(instance_id: str) -> int:
    match = re.search(r"-(\d+)c-", instance_id)
    if match is None:
        raise ValueError(f"cannot read source scale from {instance_id}")
    return int(match.group(1))


def customer_shift_map(bundle_dir: Path) -> dict[str, int]:
    manifest = json.loads((bundle_dir / "three_shift_manifest.json").read_text(encoding="utf-8"))
    counts = [int(item["kept_customer_count"]) for item in manifest["source_children"]]
    boundaries: list[int] = []
    running = 0
    for count in counts:
        running += count
        boundaries.append(running)
    output: dict[str, int] = {}
    for index in range(1, running + 1):
        shift = next(position for position, boundary in enumerate(boundaries) if index <= boundary)
        output[f"C{index:03d}"] = shift
    return output


def demand_quartiles(customers: list[Any], shifts: dict[str, int]) -> dict[str, int]:
    by_shift: dict[int, list[Any]] = defaultdict(list)
    for customer in customers:
        by_shift[shifts[customer.node_id]].append(customer)
    output: dict[str, int] = {}
    for shift, rows in by_shift.items():
        ordered = sorted(rows, key=lambda item: (float(item.demand), item.node_id))
        for rank, customer in enumerate(ordered):
            output[customer.node_id] = min(3, rank * 4 // len(ordered))
    return output


def mixed_owners(
    customers: list[Any],
    aligned: dict[str, str],
    shifts: dict[str, int],
    quartiles: dict[str, int],
    *,
    seed: int,
) -> tuple[dict[str, str], int]:
    groups: dict[tuple[int, int], list[str]] = defaultdict(list)
    for customer in customers:
        groups[(shifts[customer.node_id], quartiles[customer.node_id])].append(customer.node_id)
    rng = random.Random(seed)
    output: dict[str, str] = {}
    for block in sorted(groups):
        ids = sorted(groups[block])
        labels = [aligned[customer_id] for customer_id in ids]
        rng.shuffle(labels)
        output.update(dict(zip(ids, labels, strict=True)))
    by_id = {customer.node_id: customer for customer in customers}
    depots = sorted(set(aligned.values()))
    if len(depots) != 2:
        raise ValueError("paired ownership design currently requires exactly two depots")
    anchor = depots[0]
    target = sum(float(by_id[customer].demand) for customer, owner in aligned.items() if owner == anchor)
    current = sum(float(by_id[customer].demand) for customer, owner in output.items() if owner == anchor)
    moved_count = sum(output[customer] != aligned[customer] for customer in output)
    minimum_moved = int(len(output) * MOVED_SHARE_MIN + 0.999999)
    balance_swaps = 0
    while True:
        current_error = abs(current - target)
        best: tuple[float, tuple[int, int], str, str, int, float] | None = None
        for block in sorted(groups):
            ids = sorted(groups[block])
            left = [customer for customer in ids if output[customer] == depots[0]]
            right = [customer for customer in ids if output[customer] == depots[1]]
            for customer_left in left:
                for customer_right in right:
                    new_current = current - float(by_id[customer_left].demand) + float(by_id[customer_right].demand)
                    new_error = abs(new_current - target)
                    if new_error >= current_error - 1e-12:
                        continue
                    old_moved = int(output[customer_left] != aligned[customer_left]) + int(output[customer_right] != aligned[customer_right])
                    new_moved = int(output[customer_right] != aligned[customer_left]) + int(output[customer_left] != aligned[customer_right])
                    moved_after = moved_count - old_moved + new_moved
                    if moved_after < minimum_moved:
                        continue
                    candidate = (new_error, block, customer_left, customer_right, moved_after, new_current)
                    if best is None or candidate[:4] < best[:4]:
                        best = candidate
        if best is None:
            break
        _, _, customer_left, customer_right, moved_count, current = best
        output[customer_left], output[customer_right] = output[customer_right], output[customer_left]
        balance_swaps += 1
    return output, balance_swaps


def counts_by_key(owners: dict[str, str], key_by_customer: dict[str, Any]) -> Counter[tuple[Any, str]]:
    return Counter((key_by_customer[customer], owner) for customer, owner in owners.items())


def write_owner_map(path: Path, owners: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["customer_id", "owner_depot_id"])
        writer.writeheader()
        for customer_id in sorted(owners):
            writer.writerow({"customer_id": customer_id, "owner_depot_id": owners[customer_id]})


def build_one(instance_id: str) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    bundle_dir = instance_abs_dir(ROOT, instance_id)
    bundle = load_search_bundle(bundle_dir)
    customers = [node for node in bundle.instance.nodes if node.node_type.lower() == "c"]
    depots = [node.node_id for node in bundle.instance.nodes if node.node_type.lower() == "d"]
    scale = source_scale(instance_id)
    shifts = customer_shift_map(bundle_dir)
    quartiles = demand_quartiles(customers, shifts)
    aligned = infer_customer_home_depots(bundle.instance)
    seed = BASE_SEED + scale
    mixed, demand_balance_swaps = mixed_owners(customers, aligned, shifts, quartiles, seed=seed)

    aligned_path = OUT / "ownership_maps" / f"{instance_id}__geographic.csv"
    mixed_path = OUT / "ownership_maps" / f"{instance_id}__mixed.csv"
    write_owner_map(aligned_path, aligned)
    write_owner_map(mixed_path, mixed)

    aligned_counts = Counter(aligned.values())
    mixed_counts = Counter(mixed.values())
    shift_keys = {customer.node_id: shifts[customer.node_id] for customer in customers}
    block_keys = {customer.node_id: (shifts[customer.node_id], quartiles[customer.node_id]) for customer in customers}
    aligned_demand = {
        depot: sum(float(customer.demand) for customer in customers if aligned[customer.node_id] == depot)
        for depot in depots
    }
    mixed_demand = {
        depot: sum(float(customer.demand) for customer in customers if mixed[customer.node_id] == depot)
        for depot in depots
    }
    demand_drifts = {
        depot: abs(mixed_demand[depot] - aligned_demand[depot]) / max(aligned_demand[depot], 1e-12)
        for depot in depots
    }
    moved = sum(aligned[customer.node_id] != mixed[customer.node_id] for customer in customers)
    ratios: list[float] = []
    extras: list[float] = []
    moved_ratios: list[float] = []
    moved_extras: list[float] = []
    detail_rows: list[dict[str, Any]] = []
    for customer in customers:
        nearest = aligned[customer.node_id]
        assigned = mixed[customer.node_id]
        nearest_distance = float(bundle.instance.distance(customer.node_id, nearest))
        assigned_distance = float(bundle.instance.distance(customer.node_id, assigned))
        ratio = assigned_distance / nearest_distance if nearest_distance > 0 else 1.0
        ratios.append(ratio)
        extras.append((assigned_distance - nearest_distance) / 1000.0)
        if nearest != assigned:
            moved_ratios.append(ratio)
            moved_extras.append((assigned_distance - nearest_distance) / 1000.0)
        detail_rows.append(
            {
                "instance": instance_id,
                "customer_id": customer.node_id,
                "shift": shifts[customer.node_id] + 1,
                "demand_quartile": quartiles[customer.node_id] + 1,
                "demand_kg": float(customer.demand),
                "geographic_owner": nearest,
                "mixed_owner": assigned,
                "owner_changed": int(nearest != assigned),
                "nearest_distance_km": nearest_distance / 1000.0,
                "mixed_owner_distance_km": assigned_distance / 1000.0,
                "assigned_to_nearest_distance_ratio": ratio,
            }
        )

    max_customer_demand = max(float(customer.demand) for customer in customers)
    allowed_demand_drifts = {
        depot: max_customer_demand / max(aligned_demand[depot], 1e-12)
        for depot in depots
    }
    demand_granularity_ok = all(
        demand_drifts[depot] <= allowed_demand_drifts[depot] + 1e-12
        for depot in depots
    )
    structure_ok = (
        aligned_counts == mixed_counts
        and counts_by_key(aligned, shift_keys) == counts_by_key(mixed, shift_keys)
        and counts_by_key(aligned, block_keys) == counts_by_key(mixed, block_keys)
        and moved / len(customers) >= MOVED_SHARE_MIN
        and demand_granularity_ok
    )
    summary = {
        "instance": instance_id,
        "source_scale": scale,
        "customer_count": len(customers),
        "num_cv": bundle.instance.num_cv,
        "num_ev": bundle.instance.num_ev,
        "map_seed": seed,
        "demand_balance_swaps": demand_balance_swaps,
        "moved_customer_count": moved,
        "moved_customer_share": moved / len(customers),
        "geographic_owner_counts_json": json.dumps(dict(sorted(aligned_counts.items())), sort_keys=True),
        "mixed_owner_counts_json": json.dumps(dict(sorted(mixed_counts.items())), sort_keys=True),
        "max_owner_demand_relative_drift": max(demand_drifts.values(), default=0.0),
        "max_allowed_owner_demand_relative_drift": max(allowed_demand_drifts.values(), default=0.0),
        "median_assigned_to_nearest_distance_ratio": statistics.median(ratios),
        "mean_extra_one_way_distance_km": statistics.fmean(extras),
        "moved_customer_median_assigned_to_nearest_distance_ratio": statistics.median(moved_ratios),
        "moved_customer_mean_extra_one_way_distance_km": statistics.fmean(moved_extras),
        "geographic_map_sha256": sha256(aligned_path),
        "mixed_map_sha256": sha256(mixed_path),
        "structure_gate_pass": structure_ok,
    }
    return summary, detail_rows


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    selected = list(FORMAL_INSTANCE_ORDER)
    excluded: dict[str, str] = {}

    summaries: list[dict[str, Any]] = []
    details: list[dict[str, Any]] = []
    for instance_id in selected:
        summary, customer_rows = build_one(instance_id)
        summaries.append(summary)
        details.extend(customer_rows)

    with (OUT / "raw_runs.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(summaries[0]))
        writer.writeheader()
        writer.writerows(summaries)
    with (OUT / "customer_assignment_audit.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(details[0]))
        writer.writeheader()
        writer.writerows(details)

    passed = all(bool(row["structure_gate_pass"]) for row in summaries)
    decision = {
        "status": "PASS" if passed else "HALT",
        "search_evaluations": 0,
        "selected_instances": selected,
        "excluded_instances": excluded,
        "instance_count": len(selected),
        "paired_conditions": ["geographic customer portfolios", "spatially mixed customer portfolios"],
        "mixed_rule": "permute geographic owner labels once within service-shift and demand-quartile blocks, then use only within-block label swaps that reduce owner demand drift",
        "map_retries": 0,
        "structure_gates": {
            "same owner counts": True,
            "same owner counts within every service shift and demand quartile": True,
            "minimum moved share": MOVED_SHARE_MIN,
        "maximum owner demand drift": "no more than one largest customer load relative to that owner's aligned total",
        },
        "all_structure_gates_pass": passed,
        "next_step": "one 200-evaluation same-start wiring probe" if passed else "revise ownership generator before any search",
    }
    write_json(OUT / "decision.json", decision)
    commit = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, check=True, capture_output=True, text=True).stdout.strip()
    metadata = {
        "schema": "setp.e3.ownership_class_design.v4",
        "source_commit": commit,
        "active_manifest": str(ACTIVE_MANIFEST.relative_to(ROOT)),
        "active_manifest_sha256": sha256(ACTIVE_MANIFEST),
        "generator": str(Path(__file__).resolve().relative_to(ROOT)),
        "generator_sha256": sha256(Path(__file__).resolve()),
        "reference_design": str(SORIANO_PDF),
        "reference_design_sha256": sha256(SORIANO_PDF),
        "reference_boundary": "uses the paper's class-by-instance organization; the blocked paired permutation is this study's controlled isolation design",
        "paper_scope": "ownership class on all active L-main networks; not a population estimate for all logistics networks",
        "predecessor_design": str(PREDECESSOR.relative_to(ROOT)),
        "predecessor_decision_sha256": sha256(PREDECESSOR),
        "v4_change": "include all nine formal network sizes; powertrain availability is separated from the ownership-class design and handled by the later common fleet envelope; no map retry and no route search",
    }
    write_json(OUT / "metadata.json", metadata)

    report_lines = [
        "# 客户归属情境零搜索审计",
        "",
        f"判决：{'通过' if passed else '停止'}。本步骤只生成并检查客户归属，没有运行路线搜索。",
        "",
        "设计不再用一张大算例上的25%/50%随机错配。它直接复用全部九个正式网络；每个网络保留完全相同的客户、需求、时间窗和电网数据，只改变客户原先属于哪一家车场。车辆是否充足由下一步统一处理，不在这里用车型构成筛掉网络。",
        "",
        "第一种是地理聚集客户组合，即客户属于最近车场。第二种是空间混合客户组合：在同一配送班次、相近需求量的客户内部，只随机打乱一次车场标签；随后只在同一小组内交换能缩小两边总需求差的标签。这样每家车场在每个班次、每个需求档的客户数量不变，总需求也基本不变，差别集中在客户组合的空间结构。",
        "",
        f"共纳入 {len(selected)} 个正式网络，一个不删。所有地图只生成一次，没有根据合作结果重抽。",
        "",
        "逐网络移动比例、需求漂移和距离强度见 `raw_runs.csv`；逐客户归属见 `customer_assignment_audit.csv`。这些文件只是后续实验输入，不是论文效果结果。",
    ]
    (OUT / "report.md").write_text("\n".join(report_lines) + "\n", encoding="utf-8")
    hashes = {
        str(path.relative_to(ROOT)): sha256(path)
        for path in [
            Path(__file__).resolve(),
            OUT / "metadata.json",
            OUT / "raw_runs.csv",
            OUT / "customer_assignment_audit.csv",
            OUT / "decision.json",
            OUT / "report.md",
            *sorted((OUT / "ownership_maps").glob("*.csv")),
        ]
    }
    write_json(OUT / "artifact_hashes.json", hashes)
    return 0 if passed else 2


if __name__ == "__main__":
    raise SystemExit(main())
