from __future__ import annotations

import json
from pathlib import Path

import pytest

from dr_alns_ppo.bundle_manifest import build_manifest, validate_curriculum_manifest, validate_manifest
from setp_instance_lab.build_curriculum_instances import (
    DEFAULT_MANIFEST_OUTPUT,
    DEFAULT_TEMPLATE_MANIFEST,
    CurriculumSpec,
    build_config_for_spec,
    build_curriculum_instances,
)


REPO_ROOT = Path(__file__).resolve().parents[3]


def test_curriculum_builder_creates_representative_bundle(tmp_path: Path) -> None:
    result = build_curriculum_instances(
        root=REPO_ROOT,
        output_root=tmp_path / "generated_instances",
        manifest_output=tmp_path / "training_bundle_manifest_curriculum.json",
        specs=[CurriculumSpec("E-UK25_02", 25, 2)],
    )

    row = result["bundles"][0]
    bundle_dir = tmp_path / "generated_instances" / row["name"]
    assert (bundle_dir / "instance.json").is_file()
    assert (bundle_dir / "distance_matrix.npy").is_file()
    assert (bundle_dir / "carbon_profile.csv").is_file()
    scenario_manifest = json.loads((bundle_dir / "scenario_manifest.json").read_text(encoding="utf-8"))
    assert scenario_manifest["validation"]["passed"] is True
    assert scenario_manifest["validation"]["customer_count"] == 25

    validate_curriculum_manifest(result["manifest"], root=REPO_ROOT)


def test_curriculum_builder_filters_10001_donor_paths() -> None:
    template_manifest = json.loads((REPO_ROOT / DEFAULT_TEMPLATE_MANIFEST).read_text(encoding="utf-8"))
    template_config = dict(template_manifest["config"])
    template_config["add_event_source_paths"] = [
        str(REPO_ROOT / "models/data_bundle/raw_instances/goeke_uk/E-UK100_01.txt"),
        str(REPO_ROOT / "models/data_bundle/raw_instances/goeke_uk/E-UK25_03.txt"),
    ]

    scenario_config, manifest_config = build_config_for_spec(REPO_ROOT, template_config, CurriculumSpec("E-UK25_02", 25, 2))

    assert not any("E-UK100_01" in path for path in scenario_config.add_event_source_paths)
    assert not any("E-UK100_01" in path for path in manifest_config["add_event_source_paths"])
    assert any("E-UK25_03" in path for path in scenario_config.add_event_source_paths)


def test_validate_curriculum_manifest_accepts_pilot08_manifest_after_generation() -> None:
    manifest_path = REPO_ROOT / DEFAULT_MANIFEST_OUTPUT
    if not manifest_path.is_file():
        pytest.skip("Pilot08 manifest is generated by the curriculum builder step")

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    validate_curriculum_manifest(manifest, root=REPO_ROOT)

    assert len(manifest["train"]) == 12
    assert not any("E-UK100_01" in bundle for bundle in manifest["train"])
    assert any("E-UK100_01" in bundle for bundle in manifest["formal_eval"])


def test_validate_curriculum_manifest_rejects_10001_training_bundle() -> None:
    manifest = {
        "schema_version": "dr-alns-ppo-bundle-manifest.v1",
        "train": ["models/data_bundle/generated_instances/E-UK100_01__curric_bad"],
        "held_out": [],
        "formal_eval": ["models/data_bundle/generated_instances/E-UK100_01__d2_s3_seed1_24h_20251113"],
        "excluded_from_training_reason": {},
    }

    with pytest.raises(ValueError, match="Forbidden curriculum training bundle"):
        validate_curriculum_manifest(manifest, root=REPO_ROOT)


def test_validate_curriculum_manifest_rejects_invalid_train_metadata(tmp_path: Path) -> None:
    train = tmp_path / "E-UK25_02__curric"
    held = tmp_path / "E-UK100_03__held"
    formal = tmp_path / "E-UK100_01__formal"
    for bundle in (train, held, formal):
        bundle.mkdir()
        (bundle / "instance.json").write_text("{}", encoding="utf-8")
        (bundle / "distance_matrix.npy").write_bytes(b"placeholder")
        (bundle / "carbon_profile.csv").write_text("time_index\n", encoding="utf-8")
    (train / "scenario_manifest.json").write_text(
        json.dumps({"validation": {"passed": False, "customer_count": 25}}),
        encoding="utf-8",
    )
    manifest = {
        "schema_version": "dr-alns-ppo-bundle-manifest.v1",
        "train": [str(train)],
        "held_out": [str(held)],
        "formal_eval": [str(formal)],
        "excluded_from_training_reason": {},
    }

    with pytest.raises(ValueError, match="scenario validation did not pass"):
        validate_curriculum_manifest(manifest, root=REPO_ROOT)


def test_strict_manifest_still_rejects_euk25_training_bundle() -> None:
    manifest = build_manifest()
    manifest["train"] = ["models/data_bundle/generated_instances/E-UK25_02__curric_d2_s3_seed2_24h"]

    with pytest.raises(ValueError, match="Forbidden training bundle"):
        validate_manifest(manifest, root=REPO_ROOT)
