q_kg  # unused variable (models/src/setp_instance_lab/config.py:15)
t_min  # unused variable (models/src/setp_instance_lab/config.py:16)
q_accum_policy  # unused variable (models/src/setp_instance_lab/config.py:17)
depot_strategy  # unused variable (models/src/setp_instance_lab/config.py:34)
station_strategy  # unused variable (models/src/setp_instance_lab/config.py:35)
carbon_region  # unused variable (models/src/setp_instance_lab/models.py:24)
balance_score  # unused variable (models/src/setp_instance_lab/models.py:38)
delta_demand  # unused variable (models/src/setp_instance_lab/models.py:58)
old_ready_time  # unused variable (models/src/setp_instance_lab/models.py:59)
old_due_time  # unused variable (models/src/setp_instance_lab/models.py:60)
REPAIR_INCOMPLETE  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:43)
INTERNAL_ERROR  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:45)
energy_before_window_kwh  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:99)
before_fingerprint  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:805)
after_fingerprint  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:806)
before_violations  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:809)
after_violations  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:810)
before_carbon_cost  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:811)
after_carbon_cost  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:812)
before_emissions_kg  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:813)
after_emissions_kg  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:814)
participation_margin_before  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:815)
participation_margin_after  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:816)
minimum_participation_margin_before  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:817)
minimum_participation_margin_after  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/contracts.py:818)
donor_duty_ids  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/crossover.py:49)
duplicate_customers_removed  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/crossover.py:50)
duplicate_customers_removed  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/crossover.py:60)
dcrex  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/crossover.py:62)
introduced_edges  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:69)
redundant_customers  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:70)
missing_customers  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:71)
conflicting_customers  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:72)
donor_parent_index  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:79)
donor_route_id  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:81)
achieved_diversity  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:93)
redundant_customers  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:95)
missing_customers  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:96)
charging_candidates_evaluated  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dynamic_insertion.py:120)
candidate_feasible_count  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dynamic_insertion.py:124)
candidate_failure_reasons  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/dynamic_insertion.py:125)
_.slice_preparation_calls  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/evaluation.py:507)
_.candidate_assembly_calls  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/evaluation.py:508)
_.slice_preparation_calls  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/evaluation.py:645)
_.candidate_assembly_calls  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/evaluation.py:917)
traversal_duration_seconds  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/frvcpy_adapter.py:64)
final_energy_kwh  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/frvcpy_adapter.py:65)
_.translate  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/frvcpy_adapter.py:152)
violation_types  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/initialization.py:52)
violation_types  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/initialization.py:79)
decoded_candidates  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/integrated_private.py:114)
mechanism_improvements  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/integrated_private.py:119)
repair_improvements  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/integrated_private.py:121)
_.decoded_candidates  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/integrated_private.py:400)
_.mechanism_improvements  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/integrated_private.py:1146)
_.repair_improvements  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/integrated_private.py:1148)
base_total_cost  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/mechanical_baseline.py:49)
resulting_total_cost  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/mechanical_baseline.py:50)
incremental_total_cost  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/mechanical_baseline.py:51)
event_second  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/model.py:166)
parent_penalised_cost  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public.py:80)
pre_local_search_penalised_cost  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public.py:81)
post_local_search_penalised_cost  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public.py:82)
controller_credit  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public.py:85)
iteration_seconds  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public.py:92)
source_depot  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_assignment.py:31)
target_depot  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_assignment.py:32)
source_route_index  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_assignment.py:33)
target_route_index  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_assignment.py:34)
cost_after  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_assignment.py:37)
PUBLIC_INSTANCE_SCALE  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:49)
accepted_calls  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:75)
customer_calls  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:76)
customer_candidate_evaluations  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:77)
customer_joint_evaluations  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:78)
customer_moves_accepted  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:79)
customer_joint_only_accepted_moves  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:80)
non_improving_outputs_rejected  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:88)
_.accepted_calls  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:142)
_.customer_calls  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:147)
_.customer_candidate_evaluations  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:156)
_.customer_joint_evaluations  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:159)
_.customer_moves_accepted  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:162)
_.customer_joint_only_accepted_moves  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:165)
_.accepted_calls  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:177)
accepted_calls  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:193)
total_cost_reduction  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:197)
_.accepted_calls  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:228)
_.total_cost_reduction  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:230)
_.non_improving_outputs_rejected  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:437)
_.non_improving_outputs_rejected  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:465)
OBSERVED_MAX_SINGLE_ORDER  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/readiness.py:20)
actual_full_model_evaluations  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/runner.py:131)
effective_execution_schema  # consumers: solver/scripts/run_problem_hgs_private_technical.py:3862; solver/scripts/run_problem_hgs_dynamic_technical.py:512
effective_runtime_identity  # consumers: solver/scripts/run_problem_hgs_private_technical.py:3868; solver/scripts/run_problem_hgs_dynamic_technical.py:518; solver/tests/test_problem_hgs_execution_identity.py:445
initial_population_source_id  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/runner.py:214)
initial_population_sha256  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/runner.py:215)
independent_profit_source_id  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/runner.py:216)
independent_profit_sha256  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/runner.py:217)
independent_profit_externally_frozen  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/runner.py:218)
trajectory_sink_enabled  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/runner.py:222)
trajectory_retained_in_memory  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/runner.py:223)
proposal_engine_source_id  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/runner.py:224)
proposal_engine_sha256  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/runner.py:225)
a0_error_type  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/schedule_capture.py:24)
a0_error  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/schedule_capture.py:25)
failure_certificate  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/schedule_oracle.py:84)
reconstruction_failures  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:49)
customers_removed  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:51)
random_order_calls  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:55)
demand_order_calls  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:56)
far_order_calls  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:57)
close_order_calls  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:58)
cpu_seconds  # unused variable (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:62)
_.customers_removed  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:319)
_.reconstruction_failures  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:321)
_.reconstruction_failures  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:342)
_.reconstruction_failures  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:358)
_.cpu_seconds  # unused attribute (solver/src/setp_solver/algorithms/problem_hgs/sisr.py:383)
_._target_evaluations  # unused attribute (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:236)
accept_param  # unused variable (solver/src/setp_solver/algorithms/resetp_alns/kernel/winner.py:254)
BETTER  # unused variable (solver/src/setp_solver/algorithms/resetp_alns/runtime/outcome.py:16)
ACCEPT  # unused variable (solver/src/setp_solver/algorithms/resetp_alns/runtime/outcome.py:17)
REJECT  # unused variable (solver/src/setp_solver/algorithms/resetp_alns/runtime/outcome.py:18)
candidates_evaluated  # unused variable (solver/src/setp_solver/algorithms/resetp_alns/support/carbon_charging.py:45)
vehicle_type_semantics  # unused variable (solver/src/setp_solver/algorithms/resetp_alns/support/fleet.py:55)
protocol_id  # unused variable (solver/src/setp_solver/c8_dynamic_stream.py:96)
demand_source_customer_id  # unused variable (solver/src/setp_solver/c8_dynamic_stream.py:136)
source_distribution  # unused variable (solver/src/setp_solver/c8_dynamic_stream.py:137)
direct_return_second  # unused variable (solver/src/setp_solver/c8_dynamic_stream.py:142)
reveal_serviceable  # unused variable (solver/src/setp_solver/c8_dynamic_stream.py:143)
serviceability_reason  # unused variable (solver/src/setp_solver/c8_dynamic_stream.py:145)
CHARGING_STATION_UNIQUENESS  # unused variable (solver/src/setp_solver/check.py:33)
diesel_price_source_id  # unused variable (solver/src/setp_solver/china81.py:234)
enabled_vehicles  # unused variable (solver/src/setp_solver/main3b_backend.py:108)
full_evaluation_feasible  # unused variable (solver/src/setp_solver/main3b_backend.py:109)
evaluator_identity  # unused variable (solver/src/setp_solver/main3b_backend.py:244)
depot_charging_soc_breakpoints  # unused variable (solver/src/setp_solver/prices.py:189)
depot_charging_relative_powers  # unused variable (solver/src/setp_solver/prices.py:190)
public_charging_soc_breakpoints  # unused variable (solver/src/setp_solver/prices.py:192)
public_charging_relative_powers  # unused variable (solver/src/setp_solver/prices.py:193)
EV_DAILY_FIXED_PREMIUM_CNY  # unused variable (solver/src/setp_solver/private_instance_rebuild_20260811.py:48)
DEPOT_CHARGING_SCENARIOS  # unused variable (solver/src/setp_solver/private_instance_rebuild_20260811.py:72)
depot_charging_scenario_id  # unused variable (solver/src/setp_solver/private_instance_rebuild_20260811.py:87)
cv_direct_emissions_kg  # unused variable (solver/src/setp_solver/profit.py:46)
ev_indirect_emissions_kg  # unused variable (solver/src/setp_solver/profit.py:47)
depot_charging_kwh  # unused variable (solver/src/setp_solver/profit.py:48)
station_charging_kwh  # unused variable (solver/src/setp_solver/profit.py:49)
cm_to_inch  # unused import (solver/src/setp_solver/reporting/figures.py:8)
original_solution  # unused variable (solver/src/setp_solver/search/alns_crush.py:113)
service_start_second  # unused variable (solver/src/setp_solver/search/certificate_execution.py:48)
first_departure_second  # unused variable (solver/src/setp_solver/search/certificate_execution.py:83)
final_return_second  # unused variable (solver/src/setp_solver/search/certificate_execution.py:84)
delta_demand  # unused variable (solver/src/setp_solver/search/dynamic.py:42)
old_ready_time  # unused variable (solver/src/setp_solver/search/dynamic.py:43)
old_due_time  # unused variable (solver/src/setp_solver/search/dynamic.py:44)
defer_eligible_ids  # unused variable (solver/src/setp_solver/search/dynamic.py:92)
all_events  # unused variable (solver/src/setp_solver/search/dynamic.py:102)
stage_carbon  # unused variable (solver/src/setp_solver/search/dynamic.py:389)
source_certificate_sha256  # unused variable (solver/src/setp_solver/search/dynamic_multitrip_schedule.py:83)
charging_event_count  # unused variable (solver/src/setp_solver/search/e5_probe.py:48)
delta_intensity  # unused variable (solver/src/setp_solver/search/e5_probe.py:55)
routes_differ  # unused variable (solver/src/setp_solver/search/e5_probe.py:57)
chosen_start_second  # unused variable (solver/src/setp_solver/search/e5_probe.py:64)
greenest_start_second  # unused variable (solver/src/setp_solver/search/e5_probe.py:69)
greenest_slot  # unused variable (solver/src/setp_solver/search/e5_probe.py:70)
greenest_gamma  # unused variable (solver/src/setp_solver/search/e5_probe.py:71)
repair_delta_mode  # unused variable (solver/src/setp_solver/search/evaluation.py:61)
depot_charging_kwh  # unused variable (solver/src/setp_solver/search/execution_accounting.py:85)
station_charging_kwh  # unused variable (solver/src/setp_solver/search/execution_accounting.py:86)
E_cv_direct  # unused variable (solver/src/setp_solver/search/execution_accounting.py:89)
E_ev_indirect  # unused variable (solver/src/setp_solver/search/execution_accounting.py:90)
vehicle_type_semantics  # unused variable (solver/src/setp_solver/search/fleet.py:55)
source_depot_ids  # unused variable (solver/src/setp_solver/search/gates.py:20)
LMAIN_TO_E2_ALIAS  # unused variable (solver/src/setp_solver/search/instance_registry.py:28)
LEGACY_CONTRACT_ID  # unused variable (solver/src/setp_solver/search/multitrip_schedule.py:52)
saved_charge_start_second  # unused variable (solver/src/setp_solver/search/multitrip_schedule.py:136)
saved_charge_end_second  # unused variable (solver/src/setp_solver/search/multitrip_schedule.py:137)
electricity_cost_cny  # unused variable (solver/src/setp_solver/search/multitrip_schedule.py:138)
interface_summary  # unused variable (solver/src/setp_solver/search/scout.py:21)
adapter_needed  # unused variable (solver/src/setp_solver/search/scout.py:22)
_.Axes  # unused attribute (solver/src/setp_solver/search/scout.py:100)
_.Figure  # unused attribute (solver/src/setp_solver/search/scout.py:101)
_.draw_if_interactive  # unused attribute (solver/src/setp_solver/search/scout.py:103)
io  # unused import (solver/src/setp_solver/search/winner_nondeterminism.py:12)
SMALL_BUNDLE  # unused variable (solver/tests/test_e2_alns_throughput.py:33)
structures_two  # unused variable (solver/tests/test_e3_medium_ownership_diagnostic.py:53)
cancel_futures  # unused variable (solver/tests/test_e7_formal_resumable_runner.py:200)
wait  # unused variable (solver/tests/test_e7_formal_resumable_runner.py:200)
_.__package__  # unused attribute (solver/tests/test_profit.py:289)
SEARCH  # unused variable (solver/tests/test_resetp_alns_full_independence.py:12)
freeze  # unused variable (solver/tests/test_solomon_external_strong_baseline_interface_20260717.py:423)
freeze  # unused variable (solver/tests/test_solomon_external_strong_baseline_interface_20260717.py:447)
_._STOP_SIGNAL  # unused attribute (solver/tests/test_solomon_external_strong_baseline_interface_20260717.py:480)
_._STOP_SIGNAL  # unused attribute (solver/tests/test_solomon_external_strong_baseline_interface_20260717.py:497)
freeze  # unused variable (solver/tests/test_solomon_external_strong_baseline_interface_20260717.py:528)
_count_table  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:253)
_.destroy_index  # unused method (solver/src/setp_solver/algorithms/resetp_alns/kernel/winner.py:368)
_.repair_index  # unused method (solver/src/setp_solver/algorithms/resetp_alns/kernel/winner.py:371)
event_payload_sha256  # unused function (solver/src/setp_solver/c8_dynamic_stream.py:941)
_.for_seed  # unused method (solver/src/setp_solver/main3b_backend.py:246)
_.with_stream  # unused method (solver/src/setp_solver/main3b_backend.py:249)
cm_to_inch  # unused function (solver/src/setp_solver/reporting/style.py:72)
__getattr__  # unused function (solver/src/setp_solver/search/alns_wouda.py:22)
__class_getitem__  # unused function (solver/src/setp_solver/search/candidates.py:55)
_route_set_distance  # unused function (solver/src/setp_solver/search/candidates.py:1573)
dynamic_final_failure_payload_for_test  # unused function (solver/src/setp_solver/search/dynamic.py:897)
formal_instance_names  # unused function (solver/src/setp_solver/search/instance_registry.py:41)
_.suptitle  # unused method (solver/src/setp_solver/search/scout.py:94)
__getattr__  # unused function (solver/src/setp_solver/search/winner_operators.py:19)
_.cancel  # unused method (solver/tests/test_e7_formal_resumable_runner.py:190)
_.shutdown  # unused method (solver/tests/test_e7_formal_resumable_runner.py:200)
_.wait  # unused method (solver/tests/test_solomon_external_strong_baseline_interface_20260717.py:474)

# P124: fields consumed through dataclass serialization or solver/scripts,
# which are intentionally outside the Vulture source set.
new_ready_time
new_due_time
current_solution_raw_cost
current_solution_penalized_cost
physical_feasible
fairness_feasible
violation_counts
outer_repair_calls
fleet_cap_semantics
total_emissions_kg
public_charging_curve_id
served_customer_ids
generation_statistics
make_shared_initial_solution
charging_action_from_dict
evaluate_rebuild_solution
complete_china81_route_skeleton

# P124: the protected evaluator and protected charging implementation retain
# their established callable surface unchanged.
arrive_station
reached_target
score_reference
score_candidate
model_cost
solve_charging
_.rewards  # unused property (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:179)
_.ready_for_charging_rebuild  # unused property (solver/src/setp_solver/algorithms/problem_hgs/hybrid_decoder.py:101)
_try_cv_to_ev  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:961)
_try_ev_to_cv  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:1010)
_worst_customer_by_distance_contribution  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:1171)
_scan_route_distance  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/winner.py:3534)
_.legal_pairs  # unused property (solver/src/setp_solver/algorithms/resetp_alns/runtime/select.py:49)
_carbon_row_for_slot_index  # unused function (solver/src/setp_solver/cost.py:1287)
_.order_by_id  # unused property (solver/src/setp_solver/main3b_backend.py:144)
_.unserved_customer_ids  # unused property (solver/src/setp_solver/main3b_backend.py:218)
_.charging_occupancy_fee  # unused property (solver/src/setp_solver/prices.py:195)
_.cross_site_service_cost  # unused property (solver/src/setp_solver/prices.py:199)
_.diesel_emission_factor  # unused property (solver/src/setp_solver/prices.py:203)
__new__  # unused function (solver/src/setp_solver/search/candidates.py:51)
myopic_rolling_policy  # unused function (solver/src/setp_solver/search/dynamic.py:131)
_.booked_route_ids  # unused property (solver/src/setp_solver/search/execution_accounting.py:199)
trajectory_dicts  # unused function (solver/src/setp_solver/algorithms/problem_hgs/education.py:730)
exploratory_type_hints  # unused function (solver/src/setp_solver/algorithms/resetp_alns/support/order_decoder.py:78)
record_timing  # unused function (solver/src/setp_solver/algorithms/resetp_alns/support/timing.py:52)
exploratory_type_hints  # unused function (solver/src/setp_solver/search/order_decoder.py:78)
record_timing  # unused function (solver/src/setp_solver/search/timing.py:52)
_.node_operator_names  # unused property (solver/src/setp_solver/algorithms/problem_hgs/kernel_proposals.py:359)
__getattr__  # unused function (solver/src/setp_solver/algorithms/resetp_alns/__init__.py:25)
identity_repair  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:847)
run_design_templates  # unused function (solver/src/setp_solver/reporting/runner.py:90)
_.wait  # unused method (solver/tests/test_solomon_external_strong_baseline_interface_20260717.py:350)
_seed_route_limit  # unused function (solver/src/setp_solver/algorithms/resetp_alns/support/construction.py:521)
depot_site_power_kw_shadow  # unused function (solver/src/setp_solver/field_rename_compat.py:69)
_seed_route_limit  # unused function (solver/src/setp_solver/search/construction.py:538)
_.wait  # unused method (solver/tests/test_solomon_sintef_formal_runner_20260717.py:160)
_rotations  # unused function (solver/src/setp_solver/algorithms/problem_hgs/vidal_compound.py:518)
feasible_route_customers  # unused import (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:34)
feasible_route_distance  # unused import (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:34)
_apply_path_operator  # unused function (solver/src/setp_solver/search/candidates.py:1112)
iter_formal_bundles  # unused function (solver/src/setp_solver/search/instance_registry.py:64)
baseline_result_to_dict  # unused import (solver/src/setp_solver/search/metaheuristic_baseline_runner.py:32)
_ranked_repair_routes  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:1054)
_scale_bar  # unused function (solver/src/setp_solver/reporting/figures.py:728)
_.trip_counts_by_vehicle  # unused property (solver/src/setp_solver/algorithms/problem_hgs/hybrid_decoder.py:105)
read_public_instance  # unused function (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:53)
schedule_capture_sink  # unused function (solver/src/setp_solver/algorithms/problem_hgs/schedule_capture.py:35)
write_t9_dynamic_csv  # unused import (solver/src/setp_solver/search/formal_runner.py:39)
proposal_stages  # unused function (solver/src/setp_solver/algorithms/problem_hgs/proposals.py:481)
_repair_route_delta_score  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:1112)
_first_number  # unused function (solver/src/setp_solver/algorithms/resetp_alns/support/fleet.py:305)
run_build_samples  # unused function (solver/src/setp_solver/reporting/runner.py:78)
_first_number  # unused function (solver/src/setp_solver/search/fleet.py:305)
proposal_final_stages  # unused function (solver/src/setp_solver/algorithms/problem_hgs/proposals.py:493)
proposal_elite_route  # unused function (solver/src/setp_solver/algorithms/problem_hgs/proposals.py:506)
proposal_post_mechanism_route  # unused function (solver/src/setp_solver/algorithms/problem_hgs/proposals.py:519)
_.get_repaired  # unused method (solver/src/setp_solver/algorithms/resetp_alns/support/charging.py:204)
_.put_repaired  # unused method (solver/src/setp_solver/algorithms/resetp_alns/support/charging.py:216)
curve_from_id  # unused function (solver/src/setp_solver/charging_curve.py:683)
multi_customer_removal  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:650)
_.best_penalised  # unused method (solver/src/setp_solver/algorithms/problem_hgs/bi_objective_population.py:308)
_ranked_insert_positions  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:1072)
_.truth_boundary_statistics  # unused property (solver/src/setp_solver/algorithms/problem_hgs/kernel_proposals.py:371)
ev_profile_arc_energy_kwh  # unused function (solver/src/setp_solver/cost.py:1078)
route_distance_m  # unused function (solver/src/setp_solver/private_instance_rebuild_20260811.py:372)
_.register_started_or_completed  # unused method (solver/src/setp_solver/search/execution_accounting.py:316)
mutated_type_hints  # unused function (solver/src/setp_solver/algorithms/resetp_alns/support/order_decoder.py:84)
mutated_type_hints  # unused function (solver/src/setp_solver/search/order_decoder.py:84)
write_t9_dynamic_csv  # unused function (solver/src/setp_solver/search/dynamic.py:826)
_EvalOrRuntimeStop  # unused class (solver/src/setp_solver/algorithms/resetp_alns/kernel/alns_core.py:224)
_.score_route  # unused method (solver/src/setp_solver/algorithms/resetp_alns/support/charging.py:247)
_.repaired_key  # unused method (solver/src/setp_solver/algorithms/resetp_alns/support/charging.py:178)
run_lns_policy_baseline  # unused function (solver/src/setp_solver/search/lns_policy_kernel.py:118)
_winner_kernel_payload  # unused function (solver/src/setp_solver/search/winner_nondeterminism.py:731)
run_e2_alns_final  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/winner.py:1442)
_._improve_offspring  # unused method (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:236)
run_f5b_carbon_stress  # unused function (solver/src/setp_solver/reporting/runner.py:187)
_algorithm_rows  # unused function (solver/src/setp_solver/reporting/samples.py:202)
decode_winner_action  # unused function (solver/src/setp_solver/algorithms/resetp_alns/kernel/winner.py:522)
ExactDynamicSuffixProposalEngine  # unused class (solver/src/setp_solver/algorithms/problem_hgs/proposals.py:290)
build_customer_assignment_hgs  # unused function (solver/src/setp_solver/algorithms/problem_hgs/public_search.py:267)
_phase0_solutions  # unused function (solver/src/setp_solver/search/alns_crush.py:528)
__getattr__  # unused function (solver/src/setp_solver/search/__init__.py:37)
build_public_dcrex_hgs  # unused function (solver/src/setp_solver/algorithms/problem_hgs/public.py:478)
route_pair_metrics  # unused function (solver/src/setp_solver/algorithms/problem_hgs/dcrex.py:257)
_lowest_carbon_gap_start  # unused function (solver/src/setp_solver/search/multitrip_schedule.py:2536)
selective_duty_exchange  # unused function (solver/src/setp_solver/algorithms/problem_hgs/crossover.py:205)
build_production_problem  # unused function (solver/src/setp_solver/main3b_backend.py:953)
write_c8_stream  # unused function (solver/src/setp_solver/c8_dynamic_stream.py:642)
validate_shifted_solution  # unused function (solver/src/setp_solver/private_instance_rebuild_20260811.py:272)
_route_travel_lower_bound  # unused function (solver/src/setp_solver/algorithms/resetp_alns/support/charging.py:1431)
_route_travel_lower_bound  # unused function (solver/src/setp_solver/search/charging.py:760)
_.fleet_snapshot  # unused method (solver/src/setp_solver/main3b_backend.py:649)
_evaluate_public_moves  # unused function (solver/src/setp_solver/algorithms/problem_hgs/public.py:1064)
run_formal_backfill  # unused function (solver/src/setp_solver/reporting/runner.py:97)

# Retained contract fields, dynamic entry points, and an upstream-patched class.
before_cost
after_cost
route_distance
build_integrated_public_hgs
GeneticAlgorithm
_.full_information_static  # unused method (solver/src/setp_solver/main3b_backend.py:503)
dcrex_duty_exchange  # unused function (solver/src/setp_solver/algorithms/problem_hgs/crossover.py:65)
_.mechanical_dispatch  # unused method (solver/src/setp_solver/main3b_backend.py:398)
dcrex_repair  # unused function (solver/src/setp_solver/algorithms/problem_hgs/repair.py:40)
MechanismPrescriptionController  # unused class (solver/src/setp_solver/algorithms/resetp_alns/support/mechanism_prescription.py:87)
